build:
	echo "TODO"

dev:
	echo "TODO"

run:
	node . examples/001-hello-world/hello-world.js

test:
	echo "TODO"

benchmark:
	echo "TODO"

publish-local:
	-sudo npm uninstall --global @raiment/sea-jsx
	sudo npm install --global .

publish:
	npm publish
