ensure:
	echo "TODO"

build:
	echo "TODO"

dev:
	echo "TODO"

run:
	node . 

test:
	npx jest --verbose .

benchmark:
	echo "TODO"

publish-local:
	-sudo npm uninstall --global @raiment/sea-todo
	sudo npm install --global .

publish:
	npm publish
