projects:
    - title: Modular stuff
    - title: Sea Platform
guidebook:
    scenarios:
        - title: Track workout
        - title: Day hike
        - title: Solo roadtrip
    workouts:
        - title: Track workout
        - checklist:
              - 2x400, 1/4 mile rest
