ensure:
	echo "TODO"

build:
	echo "TODO"

dev:
	npx nodemon --watch "src/**/*" --exec make run

run:
	node . 

test:
	npx jest --verbose .

benchmark:
	echo "TODO"

publish-local:
	-sudo npm uninstall --global @raiment/sea-jest
	sudo npm install --global .

publish:
	npm publish --access public