name: Unit Tests
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        working-directory: source/lib/core
        run: |
          npm install
          make test
