name: Unit Tests
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest    
    container:
        image: ".devcontainer/Dockerfile"
    steps:
      - uses: actions/checkout@v3
      - name: environment setup
        run: source setup.sh
      - name: "@raiment/core unit tests"      
        working-directory: source/lib/core
        run: |
          echo MONOREPO_ROOT=$(MONOREPO_ROOT)
          npm install
          make test
      - name: Publish milestone 1
        working-directory: source/projects/adventure/01-milestone        
        run: |
          make ensure
          make publish
