# This is a basic workflow to help you get started with Actions
name: Unit Tests

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Name of the action
  test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run unit tests
        working-directory: source/projects/core
        run: |
          npm install
          make test
