name: Unit Tests
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - name: "@raiment/core unit tests"      
        working-directory: source/lib/core
        run: |
          export MONOREPO_ROOT=$(pwd)
          npm install
          make test
      - name: Publish milestone 1
        working-directory: source/projects/adventure/01-milestone        
        run: |
          export MONOREPO_ROOT=$(pwd)
          make ensure
          make publish
